default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  password:

development:
  <<: *default
  database: db/development

staging:
  <<: *default
  database: db/staging

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
